"""Compare two EdgeSAM checkpoints on SA-1B format data with point prompts.

This script evaluates two models on SA-1B style annotation files:
  datasets/SA-1B/
    images/<split>/*.jpg
    annotations/<split>/*.json

For each GT instance:
  1) sample one positive point prompt (random or geometric center),
  2) run both models,
  3) choose one mask from multimask outputs via strategy (oracle/score/area),
  4) collect paired statistics and visual reports.
"""

from __future__ import annotations

import argparse
import copy
import json
import os
from dataclasses import dataclass
from glob import glob
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
from PIL import Image, ImageDraw
from pycocotools import mask as mask_utils
from tqdm import tqdm

from edge_sam import SamPredictor, sam_model_registry


@dataclass
class ModelResult:
    name: str
    ious: List[float]

@dataclass
class InstanceRecord:
    case_id: int
    ann_path: str
    img_path: str
    ann_index: int
    point_x: float
    point_y: float
    iou_a: float
    iou_b: float
    delta: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser("Compare two EdgeSAM checkpoints on SA-1B")
    parser.add_argument("--data-root", default="datasets/SA-1B", help="SA-1B root")
    parser.add_argument("--split", default="val", help="Dataset split")
    parser.add_argument("--checkpoint-a", required=True, help="Checkpoint path for model A")
    parser.add_argument("--checkpoint-b", required=True, help="Checkpoint path for model B")
    parser.add_argument("--name-a", default="model_a", help="Display name for model A")
    parser.add_argument("--name-b", default="model_b", help="Display name for model B")
    parser.add_argument(
        "--point-strategy",
        default="geometric_center",
        choices=["random", "geometric_center"],
        help="Point sampling strategy",
    )
    parser.add_argument(
        "--num-multimask-outputs",
        type=int,
        default=3,
        choices=[1, 3, 4],
        help="Number of masks generated by EdgeSAM",
    )
    parser.add_argument(
        "--mask-select-a",
        default="oracle",
        choices=["oracle", "score", "area"],
        help="Mask selection strategy for model A",
    )
    parser.add_argument(
        "--mask-select-b",
        default="oracle",
        choices=["oracle", "score", "area"],
        help="Mask selection strategy for model B",
    )
    parser.add_argument("--max-images", type=int, default=-1, help="Max images to evaluate")
    parser.add_argument(
        "--max-masks-per-image",
        type=int,
        default=-1,
        help="Max GT masks evaluated per image",
    )
    parser.add_argument(
        "--max-instances",
        type=int,
        default=-1,
        help="Max GT instances evaluated globally (-1 means all)",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", default="cuda", help="cuda or cpu")
    parser.add_argument(
        "--num-extreme-cases",
        type=int,
        default=10,
        help="How many best/worst comparison cases to save as images (0 disables)",
    )
    parser.add_argument("--output-dir", default="output/sa1b_compare", help="Output directory")
    return parser.parse_args()


def decode_segmentation(segm, height: int, width: int) -> np.ndarray | None:
    if isinstance(segm, list):
        rles = mask_utils.frPyObjects(segm, height, width)
        rle = mask_utils.merge(rles)
    elif isinstance(segm, dict):
        if isinstance(segm.get("counts"), list):
            rle = mask_utils.frPyObjects(segm, height, width)
        else:
            rle = segm
    else:
        return None
    return mask_utils.decode(rle).astype(np.uint8)




def farthest_point_from_boundary(mask: np.ndarray) -> Tuple[float, float]:
    h, w = mask.shape
    fg = (mask > 0).astype(np.uint8)

    # Multi-source BFS initialized from background pixels.
    from collections import deque

    inf = np.iinfo(np.int32).max
    dist = np.full((h, w), inf, dtype=np.int32)
    q = deque()

    bg_ys, bg_xs = np.where(fg == 0)
    for y, x in zip(bg_ys.tolist(), bg_xs.tolist()):
        dist[y, x] = 0
        q.append((y, x))

    # If mask fills whole image (rare), fallback to image center.
    if not q:
        return float(w / 2.0), float(h / 2.0)

    neighbors = ((1, 0), (-1, 0), (0, 1), (0, -1))
    while q:
        y, x = q.popleft()
        nd = dist[y, x] + 1
        for dy, dx in neighbors:
            ny, nx = y + dy, x + dx
            if 0 <= ny < h and 0 <= nx < w and dist[ny, nx] > nd:
                dist[ny, nx] = nd
                q.append((ny, nx))

    fg_ys, fg_xs = np.where(fg > 0)
    fg_d = dist[fg_ys, fg_xs]
    best = int(np.argmax(fg_d))
    return float(fg_xs[best]), float(fg_ys[best])


def sample_prompt_point(mask: np.ndarray, strategy: str, rng: np.random.Generator) -> Tuple[float, float]:
    ys, xs = np.where(mask > 0)
    if len(xs) == 0:
        raise ValueError("Empty mask cannot provide prompt point")

    if strategy == "random":
        idx = int(rng.integers(0, len(xs)))
        return float(xs[idx]), float(ys[idx])

    # geometric_center: pick the interior pixel with maximum L1 distance
    # to background (multi-source BFS distance transform).
    return farthest_point_from_boundary(mask)


def compute_iou(pred_mask: np.ndarray, gt_mask: np.ndarray) -> float:
    inter = np.logical_and(pred_mask, gt_mask).sum()
    union = np.logical_or(pred_mask, gt_mask).sum()
    if union == 0:
        return 1.0 if inter == 0 else 0.0
    return float(inter) / float(union)


def select_mask_index_and_iou(
    masks: np.ndarray,
    scores: np.ndarray,
    gt_mask: np.ndarray,
    strategy: str,
) -> Tuple[int, float]:
    ious = np.array([compute_iou(m.astype(bool), gt_mask.astype(bool)) for m in masks], dtype=np.float32)
    if strategy == "oracle":
        idx = int(np.argmax(ious))
        return idx, float(ious[idx])
    if strategy == "score":
        idx = int(np.argmax(scores))
        return idx, float(ious[idx])
    if strategy == "area":
        areas = np.array([(m > 0).sum() for m in masks], dtype=np.float32)
        idx = int(np.argmax(areas))
        return idx, float(ious[idx])
    raise ValueError(f"Unknown strategy: {strategy}")


def describe(values: np.ndarray) -> Dict[str, float]:
    return {
        "mean": float(np.mean(values)),
        "median": float(np.median(values)),
        "std": float(np.std(values)),
        "min": float(np.min(values)),
        "max": float(np.max(values)),
        "p25": float(np.percentile(values, 25)),
        "p75": float(np.percentile(values, 75)),
        "iou@0.5": float(np.mean(values >= 0.5)),
        "iou@0.75": float(np.mean(values >= 0.75)),
        "iou@0.9": float(np.mean(values >= 0.9)),
    }


def plot_histograms(iou_a: np.ndarray, iou_b: np.ndarray, name_a: str, name_b: str, out_dir: str) -> None:
    import matplotlib.pyplot as plt

    os.makedirs(out_dir, exist_ok=True)

    bins = np.linspace(0.0, 1.0, 41)

    plt.figure(figsize=(9, 5))
    plt.hist(iou_a, bins=bins, alpha=0.55, label=name_a)
    plt.hist(iou_b, bins=bins, alpha=0.55, label=name_b)
    plt.xlabel("IoU")
    plt.ylabel("Count")
    plt.title("IoU distribution")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "hist_iou_overlay.png"), dpi=160)
    plt.close()

    delta = iou_b - iou_a
    plt.figure(figsize=(9, 5))
    plt.hist(delta, bins=41, alpha=0.85, color="#4e79a7")
    plt.axvline(0.0, color="black", linestyle="--", linewidth=1)
    plt.xlabel(f"IoU delta ({name_b} - {name_a})")
    plt.ylabel("Count")
    plt.title("IoU delta distribution")
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "hist_delta.png"), dpi=160)
    plt.close()

    sorted_a = np.sort(iou_a)
    sorted_b = np.sort(iou_b)
    y = np.linspace(0.0, 1.0, len(sorted_a), endpoint=True)
    plt.figure(figsize=(9, 5))
    plt.plot(sorted_a, y, label=name_a)
    plt.plot(sorted_b, y, label=name_b)
    plt.xlabel("IoU")
    plt.ylabel("CDF")
    plt.title("IoU CDF")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "cdf_iou.png"), dpi=160)
    plt.close()


def build_predictor(checkpoint: str, device: str) -> SamPredictor:
    model = sam_model_registry["edge_sam"](checkpoint=checkpoint)
    model.to(device)
    model.eval()
    return SamPredictor(model)


def evaluate(args: argparse.Namespace) -> Tuple[ModelResult, ModelResult, Dict[str, float], int, int, List[InstanceRecord]]:
    rng = np.random.default_rng(args.seed)

    predictor_a = build_predictor(args.checkpoint_a, args.device)
    predictor_b = build_predictor(args.checkpoint_b, args.device)

    ann_dir = os.path.join(args.data_root, "annotations", args.split)
    img_dir = os.path.join(args.data_root, "images", args.split)
    ann_files = sorted(glob(os.path.join(ann_dir, "*.json")))
    if args.max_images > 0:
        ann_files = ann_files[: args.max_images]

    ious_a: List[float] = []
    ious_b: List[float] = []
    per_instance_records: List[InstanceRecord] = []
    total_images = 0
    total_instances = 0

    for ann_path in tqdm(ann_files, desc="Evaluating SA-1B"):
        with open(ann_path, "r") as f:
            ann_json = json.load(f)

        image_info = ann_json.get("image", {})
        file_name = image_info.get("file_name")
        if not file_name:
            file_name = f"{Path(ann_path).stem}.jpg"

        img_path = os.path.join(img_dir, file_name)
        if not os.path.exists(img_path):
            # fallback for custom naming
            candidate = os.path.join(img_dir, f"{Path(ann_path).stem}.jpg")
            if not os.path.exists(candidate):
                continue
            img_path = candidate

        image = np.array(Image.open(img_path).convert("RGB"))
        height, width = image.shape[:2]

        predictor_a.set_image(image)
        predictor_b.set_image(image)

        records = list(enumerate(ann_json.get("annotations", [])))
        if args.max_masks_per_image > 0 and len(records) > args.max_masks_per_image:
            select_ids = rng.choice(len(records), size=args.max_masks_per_image, replace=False)
            records = [records[i] for i in sorted(select_ids.tolist())]

        valid_any = False
        for ann_index, record in records:
            gt_mask = decode_segmentation(record.get("segmentation"), height, width)
            if gt_mask is None or gt_mask.sum() == 0:
                continue

            x, y = sample_prompt_point(gt_mask, args.point_strategy, rng)
            point_coords = np.array([[x, y]], dtype=np.float32)
            point_labels = np.array([1], dtype=np.int32)

            masks_a, scores_a, _ = predictor_a.predict(
                point_coords=point_coords,
                point_labels=point_labels,
                num_multimask_outputs=args.num_multimask_outputs,
            )
            masks_b, scores_b, _ = predictor_b.predict(
                point_coords=point_coords,
                point_labels=point_labels,
                num_multimask_outputs=args.num_multimask_outputs,
            )

            _, iou_a = select_mask_index_and_iou(masks_a, scores_a, gt_mask, args.mask_select_a)
            _, iou_b = select_mask_index_and_iou(masks_b, scores_b, gt_mask, args.mask_select_b)
            ious_a.append(iou_a)
            ious_b.append(iou_b)
            total_instances += 1
            valid_any = True
            per_instance_records.append(
                InstanceRecord(
                    case_id=total_instances,
                    ann_path=ann_path,
                    img_path=img_path,
                    ann_index=ann_index,
                    point_x=x,
                    point_y=y,
                    iou_a=iou_a,
                    iou_b=iou_b,
                    delta=iou_b - iou_a,
                )
            )
            if 0 < args.max_instances <= total_instances:
                break

        if valid_any:
            total_images += 1
        if 0 < args.max_instances <= total_instances:
            break

    if not ious_a:
        raise RuntimeError("No valid instances found. Check dataset paths and annotation format.")

    iou_a_np = np.array(ious_a, dtype=np.float32)
    iou_b_np = np.array(ious_b, dtype=np.float32)
    delta = iou_b_np - iou_a_np

    summary = {
        "delta_mean": float(np.mean(delta)),
        "delta_median": float(np.median(delta)),
        "delta_std": float(np.std(delta)),
        "better_b_ratio": float(np.mean(delta > 0)),
        "better_a_ratio": float(np.mean(delta < 0)),
        "tie_ratio": float(np.mean(delta == 0)),
    }

    return (
        ModelResult(args.name_a, ious_a),
        ModelResult(args.name_b, ious_b),
        summary,
        total_images,
        total_instances,
        per_instance_records,
    )


def make_overlay(image: np.ndarray, mask: np.ndarray, point_x: float, point_y: float, color: Tuple[int, int, int]) -> Image.Image:
    base = Image.fromarray(image.astype(np.uint8), mode="RGB")
    overlay = Image.new("RGB", base.size, color)
    alpha = Image.fromarray((mask.astype(np.uint8) * 110), mode="L")
    blended = Image.composite(overlay, base, alpha)
    draw = ImageDraw.Draw(blended)
    r = 5
    draw.ellipse((point_x - r, point_y - r, point_x + r, point_y + r), fill=(255, 255, 0), outline=(0, 0, 0), width=1)
    return blended


def save_extreme_case_artifacts(
    args: argparse.Namespace,
    case: InstanceRecord,
    rank_label: str,
    out_dir: str,
    predictor_a: SamPredictor,
    predictor_b: SamPredictor,
) -> Dict[str, object]:
    with open(case.ann_path, "r") as f:
        ann_json = json.load(f)
    ann = ann_json.get("annotations", [])[case.ann_index]

    image = np.array(Image.open(case.img_path).convert("RGB"))
    h, w = image.shape[:2]
    gt_mask = decode_segmentation(ann.get("segmentation"), h, w)
    if gt_mask is None:
        raise RuntimeError(f"Cannot decode segmentation for case {case.case_id}")

    point_coords = np.array([[case.point_x, case.point_y]], dtype=np.float32)
    point_labels = np.array([1], dtype=np.int32)

    predictor_a.set_image(image)
    predictor_b.set_image(image)
    masks_a, scores_a, _ = predictor_a.predict(
        point_coords=point_coords,
        point_labels=point_labels,
        num_multimask_outputs=args.num_multimask_outputs,
    )
    masks_b, scores_b, _ = predictor_b.predict(
        point_coords=point_coords,
        point_labels=point_labels,
        num_multimask_outputs=args.num_multimask_outputs,
    )
    idx_a, _ = select_mask_index_and_iou(masks_a, scores_a, gt_mask, args.mask_select_a)
    idx_b, _ = select_mask_index_and_iou(masks_b, scores_b, gt_mask, args.mask_select_b)
    pred_a = masks_a[idx_a].astype(np.uint8)
    pred_b = masks_b[idx_b].astype(np.uint8)

    case_dir = os.path.join(out_dir, rank_label)
    os.makedirs(case_dir, exist_ok=True)
    stem = f"rank_{rank_label}_case_{case.case_id:06d}"
    case_prefix = os.path.join(case_dir, stem)

    original = Image.fromarray(image.astype(np.uint8), mode="RGB")
    original_with_point = copy.deepcopy(original)
    draw = ImageDraw.Draw(original_with_point)
    r = 5
    draw.ellipse(
        (case.point_x - r, case.point_y - r, case.point_x + r, case.point_y + r),
        fill=(255, 255, 0),
        outline=(0, 0, 0),
        width=1,
    )
    original_with_point.save(f"{case_prefix}_original.png")
    Image.fromarray((gt_mask > 0).astype(np.uint8) * 255, mode="L").save(f"{case_prefix}_gt.png")
    Image.fromarray((pred_a > 0).astype(np.uint8) * 255, mode="L").save(f"{case_prefix}_pred_a.png")
    Image.fromarray((pred_b > 0).astype(np.uint8) * 255, mode="L").save(f"{case_prefix}_pred_b.png")
    make_overlay(image, (gt_mask > 0).astype(np.uint8), case.point_x, case.point_y, (0, 255, 0)).save(
        f"{case_prefix}_overlay_gt.png"
    )
    make_overlay(image, (pred_a > 0).astype(np.uint8), case.point_x, case.point_y, (255, 0, 0)).save(
        f"{case_prefix}_overlay_a.png"
    )
    make_overlay(image, (pred_b > 0).astype(np.uint8), case.point_x, case.point_y, (0, 128, 255)).save(
        f"{case_prefix}_overlay_b.png"
    )

    record = {
        "rank_label": rank_label,
        "case_id": case.case_id,
        "ann_path": case.ann_path,
        "img_path": case.img_path,
        "ann_index": case.ann_index,
        "point": [case.point_x, case.point_y],
        "iou_a": case.iou_a,
        "iou_b": case.iou_b,
        "delta": case.delta,
        "artifacts_prefix": case_prefix,
    }
    with open(f"{case_prefix}_meta.json", "w") as f:
        json.dump(record, f, indent=2)
    return record


def save_extreme_cases(args: argparse.Namespace, per_instance_records: List[InstanceRecord]) -> Dict[str, List[Dict[str, object]]]:
    if args.num_extreme_cases <= 0 or not per_instance_records:
        return {"best": [], "worst": []}

    sorted_records = sorted(per_instance_records, key=lambda x: x.delta)
    k = min(args.num_extreme_cases, len(sorted_records))
    worst = sorted_records[:k]
    best = list(reversed(sorted_records[-k:]))

    out_dir = os.path.join(args.output_dir, "extreme_cases")
    predictor_a = build_predictor(args.checkpoint_a, args.device)
    predictor_b = build_predictor(args.checkpoint_b, args.device)
    saved_best: List[Dict[str, object]] = []
    saved_worst: List[Dict[str, object]] = []

    for idx, case in enumerate(tqdm(best, desc="Saving best cases"), start=1):
        saved_best.append(
            save_extreme_case_artifacts(
                args,
                case,
                rank_label=f"best_{idx:02d}",
                out_dir=out_dir,
                predictor_a=predictor_a,
                predictor_b=predictor_b,
            )
        )
    for idx, case in enumerate(tqdm(worst, desc="Saving worst cases"), start=1):
        saved_worst.append(
            save_extreme_case_artifacts(
                args,
                case,
                rank_label=f"worst_{idx:02d}",
                out_dir=out_dir,
                predictor_a=predictor_a,
                predictor_b=predictor_b,
            )
        )
    return {"best": saved_best, "worst": saved_worst}


def main() -> None:
    args = parse_args()
    os.makedirs(args.output_dir, exist_ok=True)

    with torch.no_grad():
        res_a, res_b, cmp_stats, n_images, n_instances, per_instance_records = evaluate(args)

    iou_a = np.array(res_a.ious, dtype=np.float32)
    iou_b = np.array(res_b.ious, dtype=np.float32)

    summary = {
        "config": {
            "data_root": args.data_root,
            "split": args.split,
            "checkpoint_a": args.checkpoint_a,
            "checkpoint_b": args.checkpoint_b,
            "name_a": args.name_a,
            "name_b": args.name_b,
            "point_strategy": args.point_strategy,
            "num_multimask_outputs": args.num_multimask_outputs,
            "mask_select_a": args.mask_select_a,
            "mask_select_b": args.mask_select_b,
            "seed": args.seed,
            "max_images": args.max_images,
            "max_masks_per_image": args.max_masks_per_image,
            "max_instances": args.max_instances,
            "num_extreme_cases": args.num_extreme_cases,
        },
        "dataset": {
            "num_images": n_images,
            "num_instances": n_instances,
        },
        "model_a": describe(iou_a),
        "model_b": describe(iou_b),
        "comparison": cmp_stats,
    }

    with torch.no_grad():
        extreme_cases = save_extreme_cases(args, per_instance_records)
    summary["extreme_cases"] = extreme_cases

    plot_histograms(iou_a, iou_b, args.name_a, args.name_b, args.output_dir)

    with open(os.path.join(args.output_dir, "summary.json"), "w") as f:
        json.dump(summary, f, indent=2)

    np.save(os.path.join(args.output_dir, "iou_a.npy"), iou_a)
    np.save(os.path.join(args.output_dir, "iou_b.npy"), iou_b)

    print("=" * 70)
    print(f"Images used     : {n_images}")
    print(f"Instances used  : {n_instances}")
    print(f"Mask select A  : {args.mask_select_a}")
    print(f"Mask select B  : {args.mask_select_b}")
    print(f"{args.name_a} mIoU : {summary['model_a']['mean']:.4f}")
    print(f"{args.name_b} mIoU : {summary['model_b']['mean']:.4f}")
    print(f"Delta (B - A)   : {summary['comparison']['delta_mean']:.4f}")
    print(f"B better ratio  : {summary['comparison']['better_b_ratio']:.3f}")
    print(f"A better ratio  : {summary['comparison']['better_a_ratio']:.3f}")
    print(f"Saved best/worst: {len(summary['extreme_cases']['best'])}/{len(summary['extreme_cases']['worst'])}")
    print(f"Extreme dir     : {os.path.join(args.output_dir, 'extreme_cases')}")
    print(f"Artifacts saved : {args.output_dir}")
    print("=" * 70)


if __name__ == "__main__":
    main()
